DEFAULT_TARGETS: list[str] = [
    "https://fachost.cloud/",
    "https://my.rfchost.com/",
    "https://app.vmiss.com/",
    "https://acck.io/",
    "https://console.po0.com/",
    "https://akile.io/",
    "https://greencloudvps.com/",
    "https://app.kaze.network/",
    "https://bgp.gd/",
    "https://nmcloud.cc/",
    "https://my.frantech.ca/",
    "https://wawo.wiki/",
    "https://backwaves.net/",
    "https://cloud.ggvision.net/",
    "https://wap.ac/",
    "https://www.bagevm.com/",
    "https://cloud.colocrossing.com/",
    "https://www.dmit.io/",
    "https://clients.zgovps.com/",
    "https://my.racknerd.com/",
    "https://clientarea.gigsgigscloud.com/",
    "https://cloud.boil.network/",
    "https://www.vps.soy/",
    "https://cloud.bffyun.com/",
    "https://www.lycheen.com/",
    "https://cloud.tizz.yt/",
    "https://bestvm.cloud/",


]
